development:
  adapter: mysql
  database: andyurl_dev
  username: root
  password:
  host: localhost

test:
  adapter: mysql
  database: andyurl_test
  username: root
  password:
  host: localhost
  
production:
    adapter: mysql
    database: andyurl
    username: andyurl
    password: sh0rty
    host: localhost